### ISSUE TITLE
Cannot run the image by follwing readme

### ISSUE THREAD

**Issue by irzhywau** [SergeyKudrenko/prometheus-apache-exporter#4]
I tried to setup this exporter beside a httpd container using docker-compose. server status is available on http://httpd/status
and here is the httpd-metrics container that uses the image
```yaml
  httpd-metrics:
    image: sergeykudrenko/prometheus-apache-exporter:latest
    environment:
      APACHE_EXPORTER_NAME: httpd
      APACHE_EXPORTER_URL: http://httpd/status?auto
      APACHE_EXPORTER_CLUSTERS: '{"source":"http-server"}'
      APACHE_URL_SUBSTRACT_RULES: '["?",";"," HTTP", "/img/"]'
    networks:
    - portal
    ports:
    - 9090:9345
```

```
httpd-metrics_1  | Traceback (most recent call last):
httpd-metrics_1  |   File "application.py", line 7, in <module>
httpd-metrics_1  |     REGISTRY.register(Collector())
httpd-metrics_1  |   File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 24, in register
httpd-metrics_1  |     names = self._get_names(collector)
httpd-metrics_1  |   File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 64, in _get_names
httpd-metrics_1  |     for metric in desc_func():
httpd-metrics_1  |   File "/prometheus-apache-exporter/collector.py", line 256, in collect
httpd-metrics_1  |     tmp_str = root.xpath("/html/body/dl[2]/dt[%d]" % x)[0].text.strip()
httpd-metrics_1  | IndexError: list index out of range
portal_httpd-metrics_1 exited with code 1

```

What is the mess here @SergeyKudrenko
